### PR TITLE
feat: update icons

### PR DESCRIPTION
**Pull request by anoblet**
https://app.clickup.com/t/86b2een91

## Description

This PR solves # .

### Steps completed:

According to our definition of done, I have completed the following steps:

- [ ] Acceptance criteria met
- [ ] Unit tests added
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [ ] UX tested
- [ ] Browsers / platforms tested
- [ ] Rebased & ready to merge without conflicts
- [ ] Reviewed own code

### CODE REVIEW

**Review by pawelkmpt — COMMENTED** [review]
What about app name?

**Comment by anoblet** [comment]
I updated app name, and app short name. What do we want to put for app description?

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
I deployed live. Icons are good. App name is still "JW OTT Webapp". Does new name work for you locally?

**Comment by anoblet** [comment]
Strange. It works locally, though when building it does not. I've tried setting up a production .env file, though they do not seem to take effect. I've tried: .env.prod, .env.prod.local, .env.production, .env.production.local.

Edit:

Reference: 

* https://github.com/conversionxl/ott-web-app/blob/cxl-main/platforms/web/docs/build-from-source.md#modes
* https://github.com/conversionxl/ott-web-app/blob/cxl-main/platforms/web/docs/build-from-source.md#env-variables

**Comment by pawelkmpt** [comment]
> Strange. It works locally, though when building it does not. I've tried setting up a production .env file, though they do not seem to take effect. I've tried: .env.prod, .env.prod.local, .env.production, .env.production.local.

If you don't find a solution in 1h please just hardcode our strings and leave the comment in `.env` file

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
